# Generated by Django 6.0.5 on 2026-05-16 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EUDRProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_product_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('product_type', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('is_in_scope', models.BooleanField(default=False, help_text='True if product contains EUDR-covered commodities')),
                ('commodity', models.CharField(blank=True, choices=[('cattle', 'Cattle'), ('cocoa', 'Cocoa'), ('coffee', 'Coffee'), ('palm_oil', 'Palm oil'), ('rubber', 'Rubber'), ('soya', 'Soya'), ('wood', 'Wood')], max_length=20)),
                ('hs_code', models.CharField(blank=True, help_text='Harmonized System code', max_length=20)),
                ('has_geolocation', models.BooleanField(default=False)),
                ('has_dds', models.BooleanField(default=False)),
                ('is_compliant', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeolocationPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('plot_type', models.CharField(choices=[('point', 'Point (<=4 hectares)'), ('polygon', 'Polygon (>4 hectares)')], max_length=10)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('coordinates', models.JSONField()),
                ('country_risk', models.CharField(choices=[('low', 'Low risk'), ('standard', 'Standard risk'), ('high', 'High risk')], default='standard', max_length=10)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('supplier_country', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_domain', models.CharField(max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=512)),
                ('plan', models.CharField(default='starter', max_length=20)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('uninstalled_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store_name', models.CharField(blank=True, max_length=255)),
                ('store_email', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('shopify_charge_id', models.CharField(blank=True, max_length=100)),
                ('billing_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('frozen', 'Frozen'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=255)),
                ('operator_address', models.TextField(blank=True)),
                ('operator_country', models.CharField(blank=True, max_length=2)),
                ('operator_eori', models.CharField(blank=True, help_text='EU EORI number', max_length=20)),
                ('operator_email', models.EmailField(blank=True, max_length=254)),
                ('last_product_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-installed_at'],
            },
        ),
        migrations.CreateModel(
            name='DueDiligenceStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('quantity_unit', models.CharField(choices=[('kg', 'kg'), ('m3', 'm3'), ('units', 'units'), ('liters', 'litres')], default='kg', max_length=20)),
                ('country_of_production', models.CharField(max_length=2)),
                ('risk_level', models.CharField(choices=[('low', 'Low risk'), ('standard', 'Standard risk'), ('high', 'High risk')], default='standard', max_length=10)),
                ('risk_notes', models.TextField(blank=True)),
                ('mitigation_measures', models.TextField(blank=True)),
                ('eu_reference_number', models.CharField(blank=True, help_text='Assigned by EU Info System after submission', max_length=100)),
                ('eu_verification_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to EU'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eudr_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_diligence_statements', to='core.eudrproduct')),
                ('plots', models.ManyToManyField(related_name='dds_entries', to='core.geolocationplot')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dds', to='core.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='eudrproduct',
            name='plots',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.geolocationplot'),
        ),
        migrations.AddField(
            model_name='geolocationplot',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='core.shop'),
        ),
        migrations.AddField(
            model_name='eudrproduct',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eudr_products', to='core.shop'),
        ),
        migrations.CreateModel(
            name='ComplianceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log', to='core.duediligencestatement')),
                ('eudr_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log', to='core.eudrproduct')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='core.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable label (e.g. 'ERP integration')", max_length=255)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('last_4', models.CharField(max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='core.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='eudrproduct',
            index=models.Index(fields=['shop', 'is_in_scope'], name='core_eudrpr_shop_id_8c2fba_idx'),
        ),
        migrations.AddIndex(
            model_name='eudrproduct',
            index=models.Index(fields=['shop', 'is_compliant'], name='core_eudrpr_shop_id_322d62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eudrproduct',
            unique_together={('shop', 'shopify_product_id')},
        ),
        migrations.AddIndex(
            model_name='duediligencestatement',
            index=models.Index(fields=['shop', 'status'], name='core_duedil_shop_id_a30b78_idx'),
        ),
    ]
